Repository nxtlo/aiobungie, pull requests merged in 2022-02, with the labels that each got.

#126 API endpoints coverage.
  CHANGELOG.md
  aiobungie/__init__.py
  aiobungie/__init__.pyi
  aiobungie/client.py
  aiobungie/crate/__init__.py
  aiobungie/crate/__init__.pyi
  aiobungie/crate/activity.py
  aiobungie/crate/clans.py
  aiobungie/crate/fireteams.py
  aiobungie/crate/profile.py
  aiobungie/crate/user.py
  aiobungie/interfaces/factory.py
  aiobungie/interfaces/rest.py
  aiobungie/internal/_backoff.py
  aiobungie/internal/factory.py
  aiobungie/rest.py
  aiobungie/traits.py
  aiobungie/undefined.py
  aiobungie/undefined.pyi
  tests/_raw/test_client.py
Labels: enhancement

#132 Add GREEN_PIPS to ValueUIStyle enumerator
  aiobungie/crate/entity.py
Labels: bug

#146 Implement WQ API Updates.
  CHANGELOG.md
  aiobungie/__init__.py
  aiobungie/__init__.pyi
  aiobungie/crate/__init__.py
  aiobungie/crate/__init__.pyi
  aiobungie/crate/activity.py
  aiobungie/crate/clans.py
  aiobungie/crate/components.py
  aiobungie/crate/entity.py
  aiobungie/crate/friends.py
  aiobungie/crate/items.py
  aiobungie/internal/enums.py
  aiobungie/internal/factory.py
  aiobungie/internal/helpers.py
Labels: Feature

#144 Fix HTML error responses.
  CHANGELOG.md
  aiobungie/client.py
  aiobungie/error.py
  aiobungie/rest.py
  tests/_raw/test_client.py
Labels: optimization

#149 Fix various errors.
  CHANGELOG.md
  aiobungie/client.py
  aiobungie/crate/activity.py
  aiobungie/crate/components.py
  aiobungie/crate/entity.py
  aiobungie/crate/fireteams.py
  aiobungie/crate/items.py
  aiobungie/crate/records.py
  aiobungie/interfaces/factory.py
  aiobungie/internal/enums.py
  aiobungie/internal/factory.py
  aiobungie/internal/helpers.py
  aiobungie/rest.py
  aiobungie/typedefs.py
  tests/_raw/test_client.py
Labels: enhancement

#148 Initial commit.
  CHANGELOG.md
  aiobungie/__init__.py
  aiobungie/__init__.pyi
  aiobungie/client.py
  aiobungie/crate/__init__.py
  aiobungie/crate/__init__.pyi
  aiobungie/crate/activity.py
  aiobungie/crate/character.py
  aiobungie/crate/clans.py
  aiobungie/crate/entity.py
  aiobungie/crate/fireteams.py
  aiobungie/crate/profile.py
  aiobungie/crate/user.py
  aiobungie/error.py
  aiobungie/interfaces/factory.py
  aiobungie/interfaces/rest.py
  aiobungie/internal/enums.py
  aiobungie/internal/factory.py
  aiobungie/internal/helpers.py
  aiobungie/internal/time.py
  aiobungie/rest.py
  aiobungie/traits.py
  examples/hello_world.py
  examples/transfer_items.py
  examples/user_oauth2.py
  nix/clienttest-nox.py
  tests/_raw/test_client.py
Labels: enhancement, optimization
